---
# This playbook configures the virtual hosts

- name: HOSTS | Configuration file for Apache
  action: template src=etc-apache2-sites-available-karlos.j2 dest=/etc/apache2/sites-available/karlos.conf
  tags: hosts

- name: HOSTS | Enable karlos
  action: command a2ensite karlos
  tags: hosts
